### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by BlenderDefender** [BlenderDefender/blender_project_manager#15]
Hi, 
I hope it's the right place, i'd like to report an installation problem.
Here the msg i get why trying to activate the addon : 

Traceback (most recent call last):
  File "C:\3D\Blender Launcher\stable\blender-2.91.2-windows64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender_project_manager-1'

I tried with a 2.91.2 install and a fresh 2.93 alpha install.  (also with local install with the "config" directory in the "2.93" one)
Hope that help. 
In any case, thank you for making this addon, It reminded me of when i was using the old softimage XSI which had a project manager too.

_Originally posted by @STeinWi in https://github.com/BlenderDefender/blender_project_manager/issues/14#issuecomment-779444183_

**Comment by BlenderDefender** [comment]
@STeinWi I opened a new issue for this, and I have seen people having troubles exactly like this for my other addons. You have to unzip the folder, remove the "-1" suffix from the folder name (blender_project_manager-1) and zip it again. For some reason, if addon folders have names like this, Blender throws an error. I hope that helps, in case it doesn't, try to download it from the [Releases Page](https://github.com/BlenderDefender/blender_project_manager/releases)

Greetings,
Blender Defender

P.S.: You just made my day with these kind words at the end ("In any case, thank you for making this addon, It reminded me of when i was using the old softimage XSI which had a project manager too.")

**Comment by STeinWi** [comment]
Hi, 
Worked like a charm! Thanks! 
Exploring the features right now, I'll share any ideas for improvements.
Have a nice day
